
spring:
  application:
    name: real-estate
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/real_estate
    username: real_estate
    password: real_estate
#  sql:
#    init:
#      mode: always
#      data-locations: classpath*:sql/_data-mariadb.sql
  jpa:
    defer-datasource-initialization: true # hibernate create -> schema.sql -> data.sql
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback.xml